algo = input('Digite algo: ')
print(f'O tipo primitivo de {algo} é: ', type(algo))
print('Só tem espaço?', algo.isspace())
print('É um número? ', algo.isnumeric())
print('É alfabético? ', algo.isalpha())
print('É alfanumérico? ', algo.isalnum())
print('Está em maiúculas? ', algo.isupper())
print('Está em minúsculas? ', algo.islower())
print('Está capitalzada? ', algo.istitle())
