num = int(input('Digite um número: '))
n = str(num)
print(f'Analisando o número {num}...')
print(f'unidade {n[3]}')
print(f'Dezena: {n[-2]}')
print(f'Centena: {n[1]}')
print(f'Milhar: {n[0]}')
print(n[0:4:2])
