print('-'*40)
print(' '*5, '-Trabalhando com operadores-')
print('-'*40)
print('Operadores de Comparação')

print('Vamos comparar dois valores inteiros?')
num1 = int(input('Digite um número: '))
num2 = int(input('Digite outro número: '))
print(f'O valor {num1} e {num2} são iguais? {num1 == num2}')
print(f'O valor {num1} e {num2} são diferentes? {num1 != num2}')
print(f'O valor {num1} é maior que {num2}? {num1 > num2}')
print(f'O valor {num1} é menor que {num2}? {num1 < num2}')
print(f'O valor {num1} é maior ou igual a {num2}? {num1 >= num2}')
print(f'O valor {num1} é menor ou igual a {num2}? {num1 <= num2}')
